owner: spot-thought
repo: upptime
sites:
  - name: Spot Thought Website
    url: https://www.spot-thought.com
  - name: Spot Thought Console
    url: https://console.spot-thought.com
assignees:
  - benjamin-chang
status-website:
  cname: status.spot-thought.com
  logoUrl: https://www.spot-thought.com/images/logo.svg
  name: Spot Thought
  introTitle: "**Spot Thought** service status"
  introMessage: View the current and historical status and incidents
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
